#!/bin/bash

echo "🚀 GitHub Push Karne Ke Commands"
echo "================================"
echo ""
echo "Step 1: GitHub par repository banayein:"
echo "   https://github.com/new"
echo "   Name: Hospital-Management-System-MERN"
echo ""
echo "Step 2: Ye commands copy-paste karein:"
echo ""
echo "cd /Users/zainrauf/hmsfypnr/Hospital-Management-System"
echo "git remote remove origin"
echo "git remote add origin https://github.com/NamraRauf/Hospital-Management-System-MERN.git"
echo "git remote -v"
echo "git push -u origin master"
echo ""
echo "Step 3: Username aur Password enter karein"
echo "   Username: NamraRauf"
echo "   Password: Personal Access Token (GitHub settings se)"
echo ""
