#!/bin/bash

echo "🚀 Simple Push Method"
echo "===================="
echo ""
echo "Step 1: Token banayein (browser mein)"
echo "   https://github.com/settings/tokens"
echo "   Generate new token (classic)"
echo "   Scopes: repo (check)"
echo "   Token copy karein"
echo ""
echo "Step 2: Ye commands run karein:"
echo ""
echo "cd /Users/zainrauf/hmsfypnr/Hospital-Management-System"
echo "git remote set-url origin https://github.com/NamraRauf/Hospital-Management-System-MERN.git"
echo "git push -u origin master"
echo ""
echo "Step 3: Jab password puchhe:"
echo "   Username: NamraRauf"
echo "   Password: [Apna TOKEN paste karein]"
echo ""
